# Generated by Django 3.2.10 on 2022-01-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_fileuplaod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='api/img_file')),
            ],
        ),
        migrations.DeleteModel(
            name='WiseSaying',
        ),
    ]
