# pull official base image
FROM python:3.7-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1



RUN mkdir /backend

WORKDIR /backend

ADD requirements.txt /backend
ADD . /backend/
RUN pip3 install --upgrade pip
RUN pip install djangorestframework djangorestframework-jwt
#RUN pip3 install djongo
#RUN pip3 install mongoengine
#RUN pip3 install Pillow

RUN apk add --no-cache jpeg-dev zlib-dev
RUN apk add --no-cache --virtual .build-deps build-base linux-headers
RUN pip3 install -r requirements.txt

#ADD . /backend/


# RUN apk update \
#     && apk add --virtual build-deps gcc python3-dev musl-dev \
#     && apk add --no-cache mariadb-dev


# RUN apk del build-deps






