# pull official base image
#FROM python:3.7-alpine
FROM --platform=linux/x86_64 python:3.7
#-> 여기도 두 주석의 위치
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /backend

WORKDIR /backend

ADD requirements.txt /backend
ADD . /backend/
RUN pip3 install --upgrade pip

RUN pip install djangorestframework djangorestframework-jwt

#ERROR: Could not find a version that satisfies the requirement ruamel.yaml.clib==0.2.6 (from versions: 0.1.0, 0.1.2, 0.2.0, 0.2.2, 0.2.3, 0.2.4, 0.2.6)
#13 90.28 ERROR: No matching distribution found for ruamel.yaml.clib==0.2.6
# executor failed running [/bin/sh -c pip3 install -r requirements.txt]: exit code: 1
# ERROR: Service 'backend' failed to build : Build failed
RUN pip3 install -r requirements.txt
